### Get All Posts

GET http://localhost:3000/posts

### Get Post By ID
GET http://localhost:3000/posts/6963ee28f06c4d6043272148

### Create New Post
POST http://localhost:3000/posts
Content-Type: application/json

{
	"title": "Sample",
	"conetent": "Body text",
	"sender": "You"
}

### Get comments for a Post

GET http://localhost:3000/posts/6968ce8efd1f1e318c42032b/comments


### Create Comment for a Post

POST http://localhost:3000/posts/6968ce8efd1f1e318c42032b/comments
Content-Type: application/json

{
	"content": "This is a comment",
	"author": "Commenter"
}


### Update Comment

PUT http://localhost:3000/posts/comments/6968ce8efd1f1e318c42032b
Content-Type: application/json

{
	"content": "This is a comment",
	"author": "Commenter"
}
### Delete Comment

DELETE http://localhost:3000/posts/comments/6968ce8efd1f1e318c42032b
